services:
  setup-onboarding-keys:
    image: alpine:latest
    container_name: tansive-setup-keys
    volumes:
      - ./setup_onboarding_keys.sh:/setup_onboarding_keys.sh
      - ./conf:/conf
    working_dir: /conf
    command: ["sh", "-c", "apk add --no-cache openssl && sh /setup_onboarding_keys.sh"]

  postgres:
    image: postgres:16
    container_name: tansive-postgres
    depends_on:
      - setup-onboarding-keys
    environment:
      POSTGRES_USER: tansive
      POSTGRES_PASSWORD: abc@123
      POSTGRES_DB: hatchcatalog
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql/00-create-user.sql:/docker-entrypoint-initdb.d/01-create-user.sql
      - ../sql/hatchcatalog.sql:/docker-entrypoint-initdb.d/02-hatchcatalog.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tansive -d hatchcatalog"]
      interval: 10s
      timeout: 5s
      retries: 5

  tansive-server:
    image: ghcr.io/tansive/tansive/tansivesrv:latest
    container_name: tansive-server
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./conf/tansivesrv.docker.conf.updated:/etc/tansive/tansivesrv.conf
      - tansive_server_logs:/var/log/tansive
      - tansive_runtime_config:/var/tansive/runtime
    ports:
      - "8678:8678"
    restart: unless-stopped
    command: ["/app/tansivesrv", "--config", "/etc/tansive/tansivesrv.conf"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8678/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  tangent:
    image: ghcr.io/tansive/tansive/tangent-minimal:latest
    container_name: tangent
    depends_on:
      tansive-server:
        condition: service_healthy
    volumes:
      - ./conf/tangent.docker.conf.updated:/etc/tansive/tangent.conf
      - tangent_working_dir:/var/tangent
      - ../../examples/skillset_scripts:/var/tangent/scripts
      - ../../custom_scripts:/var/tangent/custom_scripts
      - tangent_logs:/var/log/tangent
    ports:
      - "8468:8468"
      - "8627:8627"
    restart: unless-stopped
    command: ["tangent", "--config", "/etc/tansive/tangent.conf"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8468/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  tansive_server_logs:
    driver: local
  tansive_runtime_config:
    driver: local
  tangent_working_dir:
    driver: local
  tangent_logs:
    driver: local
