apiVersion: 0.1.0-alpha.1
kind: SkillSet
metadata:
  name: supabase-demo
  catalog: test-catalog
  variant: test-variant
  path: /demo-skillsets
spec:
  version: "0.1.0"
  sources:
    - name: supabase-mcp-server
      runner: system.mcp.stdio
      config:
        version: "0.1.0"
        command: npx
        args:
          - -y
          - "@supabase/mcp-server-supabase@latest"
          - "--project-ref={{ .ENV.SUPABASE_PROJECT }}"
        env:
          SUPABASE_ACCESS_TOKEN: {{ .ENV.SUPABASE_ACCESS_TOKEN }}
    - name: sql-validator
      runner: system.stdiorunner
      config:
        version: "0.1.0-alpha.1"
        runtime: "python"
        script: "validate_sql.py"
        security:
          type: default
  context:
    - name: sql-permissions
      schema:
        type: object
        properties:
          allow:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
          deny:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
        required:
          - allow
          - deny
      value:
        allow:
          select:
            - support_tickets
            - support_messages
          update:
            - support_messages
        deny:
          all:
            - integration_tokens
      valueByAction:
        - action: supabase.sql.devopsadmin
          value:
            deny:
              select:
                - support_messages
            allow:
              all:
                - support_messages
                - integration_tokens
                - support_tickets
        - action: supabase.sql.develop
          value:
            allow:
              all:
                - support_tickets
                - support_messages
                - integration_tokens
            deny:
              all:
                - integration_tokens
              drop:
                - integration_tokens
                - support_tickets
                - support_messages
      attributes:
        readOnly: true
        exportedActions:
          - supabase.sql.query
          - supabase.sql.develop
          - supabase.sql.devopsadmin
  skills:
    - name: validate_sql
      source: sql-validator
      description: Validate SQL input
      inputSchema:
        type: object
        required:
          - sql
        properties:
          sql:
            type: string
      outputSchema:
        type: object
      exportedActions:
        - supabase.mcp.use
    - name: list_tables
      source: supabase-mcp-server
      exportedActions:
        - supabase.mcp.use
    - name: execute_sql
      source: supabase-mcp-server
      transform: |
        function(session, input) {
          let validationInput = {
            sql: input.query
          }
          let ret = SkillService.invokeSkill("validate_sql", validationInput);
          // if ret is not an object, throw an error
          if (typeof ret !== "object") {
            throw new Error("unable to validate input");
          }
          if(!ret.allowed) {
            throw new Error(ret.reason);
          }
          console.log("input validated");
          console.log(ret);
          return input;
        }
      exportedActions:
        - supabase.sql.query
    - name: supabase_mcp
      source: supabase-mcp-server
      description: Supabase MCP server
      exportedActions:
        - supabase.mcp.use
      annotations:
        mcp:tools: overlay
        
    - name: apply_migration
      source: supabase-mcp-server
      description: Apply a database migration
      exportedActions:
        - supabase.deploy.write

    - name: create_branch
      source: supabase-mcp-server
      description: Create a new database branch
      exportedActions:
        - supabase.deploy.write

    - name: delete_branch
      source: supabase-mcp-server
      description: Delete a database branch
      exportedActions:
        - supabase.deploy.write

    - name: deploy_edge_function
      source: supabase-mcp-server
      description: Deploy an Edge Function
      exportedActions:
        - supabase.deploy.write

    - name: execute_sql
      source: supabase-mcp-server
      description: Execute a SQL query
      exportedActions:
        - supabase.sql.query

    - name: generate_typescript_types
      source: supabase-mcp-server
      description: Generate TypeScript types
      exportedActions:
        - supabase.codegen.read

    - name: get_advisors
      source: supabase-mcp-server
      description: Get security and performance advisors
      exportedActions:
        - supabase.deploy.read

    - name: get_anon_key
      source: supabase-mcp-server
      description: Get the anonymous API key
      exportedActions:
        - supabase.project.read

    - name: get_logs
      source: supabase-mcp-server
      description: Get recent project logs
      exportedActions:
        - supabase.deploy.read

    - name: get_project_url
      source: supabase-mcp-server
      description: Get the project API URL
      exportedActions:
        - supabase.project.read

    - name: list_branches
      source: supabase-mcp-server
      description: List all database branches
      exportedActions:
        - supabase.deploy.read

    - name: list_edge_functions
      source: supabase-mcp-server
      description: List all Edge Functions
      exportedActions:
        - supabase.deploy.read

    - name: list_extensions
      source: supabase-mcp-server
      description: List all database extensions
      exportedActions:
        - supabase.deploy.read

    - name: list_migrations
      source: supabase-mcp-server
      description: List all database migrations
      exportedActions:
        - supabase.deploy.read

    - name: merge_branch
      source: supabase-mcp-server
      description: Merge a branch into production
      exportedActions:
        - supabase.deploy.write

    - name: rebase_branch
      source: supabase-mcp-server
      description: Rebase a branch onto production
      exportedActions:
        - supabase.deploy.write

    - name: reset_branch
      source: supabase-mcp-server
      description: Reset a branch to a migration version
      exportedActions:
        - supabase.deploy.write

    - name: search_docs
      source: supabase-mcp-server
      description: Search the Supabase documentation
      exportedActions:
        - supabase.docs.read